# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2603dd84e85406fb0a7d21743b3d14b5632a8da6fc619ec8fe03c7c449c9b6197d45c144db01dc06fe14472bd235345f4eab23174117532d590caa224196692

test:
  secret_key_base: 2b5b92e42561d267177b2fb7909cc1c8e753fe001641479e96e0da280f31f6171abe9ad320707f6fb4051062a64a26e3cfc5f9beca66f370b6866fbfde1900c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
